### ISSUE TITLE
Websocket connection closes on first message

### ISSUE THREAD

**Issue by Arrendy** [tegnike/nike-open-interpreter#1]
I can successfully open a websocket connection.

My message is `{"type": "chat", "text": "What are you?"}`

When I send the message, the connection immediately closes.

Logs:
```
INFO:     connection open
Loaded conversation history.
Waiting for user message...
Received user message: {"type": "chat", "text": "What are you?"}
> Errors: EOF when reading a line
Traceback (most recent call last):
File "/app/app/services/open_interpreter_service.py", line 84, in stream_open_interpreter
for chunk in interpreter.chat(message_content, display=True, stream=True):
File "/usr/local/lib/python3.11/site-packages/interpreter/core/core.py", line 87, in _streaming_chat
yield from terminal_interface(self, message)
File "/usr/local/lib/python3.11/site-packages/interpreter/terminal_interface/terminal_interface.py", line 41, in terminal_interface
message = input("> ").strip()
^^^^^^^^^^^
EOFError: EOF when reading a line
INFO:     connection closed
```

When I change my message to `{"type": "message", "text": "What are you?"}`
I get a response `{"role": "assistant", "text": "An invalid message was sent."}`

Help would be appreciated. Thank you

**Comment by tegnike** [comment]
Thanks for trying my repo!!

I checked the error but I'm sorry I couldn't understand an exact reason of it.
Actually my environment works correctly.

I checked original OI codes and this is related to the error.

```
        if display:
            yield from terminal_interface(self, message)
            return
```

So, pleas change below code like this and try it again.

```
for chunk in interpreter.chat(message_content, display=True, stream=True):
=>
for chunk in interpreter.chat(message_content, display=False, stream=True):
```

This change doesn't affect the result. Thanks!!

**Comment by MikeBirdTech** [comment]
Thank you for the response.

I figured out my mistake. The correct structure for a websocket message is `{"type": "chat", "content": "What are you?"}`

By using `text` key, it was not being extracted into the `message_content` variable. Changing to `content` worked
